version: 0.2

env:
  shell: bash
  variables:
    APPLICATION_NAME: "CoreRanAmiPipeline"
    BUCKET_PATH: "S3/CodeBuildCoreRanBucketName"

phases:
  install:
    commands:
      - dnf update -y
      - dnf install -y aws-cli sudo
      - BUCKET_NAME=$(aws ssm get-parameter --name "/${APPLICATION_NAME}/${BUCKET_PATH}" --query "Parameter.Value" --output text)
      - echo $BUCKET_NAME
      - mkdir -p ~/src/buildScripts
      - aws s3 cp s3://${BUCKET_NAME}/buildScripts/al2023/install_dependencies_al2023.sh ~/src/buildScripts
      - sh ~/src/buildScripts/install_dependencies_al2023.sh
      #- dnf install -y 'dnf-command(check-release-update)'
      #- dnf upgrade -y --releasever=2022.0.20221207
  pre_build:
    commands:
      - ls $CODEBUILD_SRC_DIR
      - ls ~/src
      - aws s3 cp s3://${BUCKET_NAME}/buildScripts/al2023/install_srsran.sh ~/src/buildScripts
  build:
    commands:
      - sh ~/src/buildScripts/install_srsran.sh
  post_build:
    commands:
      - ls /usr/local
      - ls /usr/local/bin/
      - ls /usr/local/lib/
      - ls /usr/local/lib64/
      - ls /usr/local/etc/
      - ls /usr/local/share/
      #- cp -r /etc/srsran /usr/local/etc/srsran # Only for 4G version
artifacts:
  files:
    - bin/srs*
    - bin/mbed*
    - lib/libmbed*
    - lib/libzmq*
    - lib/pkgconfig
    - lib64/**/*
    - etc/srsran/**/*
    - share/srsran/**/*
  base-directory: /usr/local/
  enable-symlinks: yes
